In [106]:
import pandas as pd
import numpy as np
import matplotlib as plt

In [107]:
data1=pd.read_csv("mydata.csv",na_values="?")

In [112]:
#print(df)
#print(df.isna().sum())
#print(df.head())
print(data1.head())

   a  b  c  d   e  f  g      h           i
0  0  0  2  1  59  1  0  False  163.316667
1  0  0  2  1  59  2  0  False  200.860000
2  0  0  2  1  59  4  0  False  154.888889
3  0  0  2  1  59  6  0  False  108.640000
4  0  0  2  1  60  1  0   True   85.466667


In [109]:
#Rename columns Name
df=pd.DataFrame(data1)
df.columns=['a','b','c','d','e','f','g','h','i']
df.head()

a  b  c  d   e  f  g      h           i
0  0  0  2  1  59  1  0  False  163.316667
1  0  0  2  1  59  2  0  False  200.860000
2  0  0  2  1  59  4  0  False  154.888889
3  0  0  2  1  59  6  0  False  108.640000
4  0  0  2  1  60  1  0   True   85.466667

In [113]:
#printing unique values in each Attribute (features)
for i in df.columns:
    print(df[i].unique())

[0 1 2]
[0 1 2 3]
[2 1]
[1 0]
[59 60 69 70 61 62 63 64 65 66 67 68 71 72 73 74 75 76 77 78 79 80 81 82
 83 84 85 86 87 88 89 90]
[1 2 4 6 3 5]
[0 3 4 2 1]
[False  True]
[ 163.31666667  200.86        154.88888889 ... 9365.45       8474.025
   82.00833333]


In [115]:
#Print Information about the data
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2043 entries, 0 to 2042
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   a       2043 non-null   int64  
 1   b       2043 non-null   int64  
 2   c       2043 non-null   int64  
 3   d       2043 non-null   int64  
 4   e       2043 non-null   int64  
 5   f       2043 non-null   int64  
 6   g       2043 non-null   int64  
 7   h       2043 non-null   bool   
 8   i       2043 non-null   float64
dtypes: bool(1), float64(1), int64(7)
memory usage: 129.8 KB
None


In [116]:
#Change Categorical data into numerical Data
from sklearn.preprocessing import LabelEncoder
LE=LabelEncoder()
encoded=LE.fit_transform(df['h'])
print(data)
# removing the original column 'Purchased' from df
df.drop("h", axis=1, inplace=True) 
# Appending the array to our dataFrame
df["h"] = encoded
# printing Dataframe
df.head()

[0 0 0 ... 0 0 1]


a  b  c  d   e  f  g           i  h
0  0  0  2  1  59  1  0  163.316667  0
1  0  0  2  1  59  2  0  200.860000  0
2  0  0  2  1  59  4  0  154.888889  0
3  0  0  2  1  59  6  0  108.640000  0
4  0  0  2  1  60  1  0   85.466667  1

In [117]:
df.shape

(2043, 9)

In [118]:
# Training the data
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(df.drop(columns=['h','i']),df['h'],test_size=0.3)
print(xtrain.shape,xtest.shape,ytrain.shape,ytest.shape)

(1430, 7) (613, 7) (1430,) (613,)


In [119]:
from sklearn.metrics import accuracy_score

In [120]:
# Perceptron Model
from sklearn.linear_model import Perceptron
model_pt = Perceptron(fit_intercept=True,shuffle=True,eta0=2,n_iter_no_change=6)
model_pt.fit(xtrain, ytrain)


Perceptron(eta0=2, n_iter_no_change=6)

In [121]:
# Training and testing accuracy of Model
print("Training accuracy is : " , accuracy_score(model_pt.predict(xtrain),ytrain))
print("Testing accuracy is : " , accuracy_score(model_pt.predict(xtest),ytest))

Training accuracy is :  0.8384615384615385
Testing accuracy is :  0.8450244698205547


In [122]:
# Decision Tree 
from sklearn.tree import DecisionTreeClassifier
#model_tree = DecisionTreeClassifier(criterion='gini', splitter='best', max_depth=None)
model_tree = DecisionTreeClassifier(criterion='entropy', splitter='random', max_depth=4)
model_tree.fit(xtrain, ytrain)


DecisionTreeClassifier(criterion='entropy', max_depth=4, splitter='random')

In [123]:
# Training and testing accuracy of Decision Tree Model
print("Training accuracy is : " , accuracy_score(model_tree.predict(xtrain),ytrain))
print("Testing accuracy is : " , accuracy_score(model_tree.predict(xtest),ytest))
# training accuracy is 1.0 and testing accuracy is .99 for gini 

Training accuracy is :  0.9090909090909091
Testing accuracy is :  0.9053833605220228


In [124]:
# Support Vector Machine Model
from sklearn.svm import SVC
model_svm=SVC(C=1.0, kernel='poly', degree=5, tol=0.002, verbose=False, max_iter=-1,
              decision_function_shape='ovr', random_state=None)
model_svm.fit(xtrain, ytrain)

SVC(degree=5, kernel='poly', tol=0.002)

In [125]:
# Training and testing accuracy of SVM Model
print("Training accuracy is : " , accuracy_score(model_svm.predict(xtrain),ytrain))
print("Testing accuracy is : " , accuracy_score(model_svm.predict(xtest),ytest))

Training accuracy is :  0.872027972027972
Testing accuracy is :  0.8711256117455138


In [126]:
# Naive Bayes Model
from sklearn.naive_bayes import GaussianNB
model_nb= GaussianNB()
model_nb.fit(xtrain, ytrain)

GaussianNB()

In [127]:
# Training and testing accuracy of Naive Bayes Model
print("Training accuracy is : " , accuracy_score(model_nb.predict(xtrain),ytrain))
print("Testing accuracy is : " , accuracy_score(model_nb.predict(xtest),ytest))

Training accuracy is :  0.83006993006993
Testing accuracy is :  0.833605220228385
